"""Staged Finalizer foundations through the Phase 6 Planner Draft boundary."""

from .catalog import (
    CATALOG_PROJECTION_VERSION,
    CATALOG_VERSION,
    CapacityPreflight,
    CatalogBuilder,
    CatalogCompleteness,
    CatalogEpisode,
    CatalogItem,
    SeasonEvidenceCatalog,
    canonical_catalog_bytes,
    catalog_detail_hash,
    compute_catalog_hash,
    compute_ids_digest,
    validate_catalog,
    verify_catalog_against_evidence,
)
from .catalog_store import CatalogBuildResult, CatalogService, CatalogStore
from .packing import PACKING_VERSION, pack_catalog, packed_catalog_bytes, unpack_catalog
from .evidence_fetch import EVIDENCE_FETCH_PROTOCOL_VERSION, EvidenceFetchResult, EvidenceFetcher, EvidenceRequest
from .planner import (
    PLANNER_DRAFT_VERSION,
    PLANNER_PROTOCOL_VERSION,
    DraftOutput,
    PlannerAction,
    PlannerDraft,
    VisualRangeRequest,
    build_initial_planner_prompt,
    planner_dependency_signature,
    validate_planner_action,
)
from .planner_service import PlannerConfig, PlannerRunResult, PlannerService
from .season_plan import SeasonPlan, SeasonPlanResult, SeasonPlanService
from .writer import WriterArtifact, WriterJob, WriterRunResult, assemble_writer_jobs, build_writer_prompt
from .writer_service import WriterConfig, WriterService

__all__ = [
    "CATALOG_PROJECTION_VERSION",
    "CATALOG_VERSION",
    "PACKING_VERSION",
    "CapacityPreflight",
    "DraftOutput",
    "EVIDENCE_FETCH_PROTOCOL_VERSION",
    "EvidenceFetchResult",
    "EvidenceFetcher",
    "EvidenceRequest",
    "CatalogBuildResult",
    "CatalogBuilder",
    "CatalogCompleteness",
    "CatalogEpisode",
    "CatalogItem",
    "CatalogService",
    "CatalogStore",
    "PLANNER_DRAFT_VERSION",
    "PLANNER_PROTOCOL_VERSION",
    "PlannerAction",
    "PlannerConfig",
    "PlannerDraft",
    "PlannerRunResult",
    "PlannerService",
    "SeasonPlan",
    "SeasonPlanResult",
    "SeasonPlanService",
    "WriterArtifact",
    "WriterConfig",
    "WriterJob",
    "WriterRunResult",
    "WriterService",
    "assemble_writer_jobs",
    "build_writer_prompt",
    "SeasonEvidenceCatalog",
    "canonical_catalog_bytes",
    "catalog_detail_hash",
    "compute_catalog_hash",
    "compute_ids_digest",
    "pack_catalog",
    "packed_catalog_bytes",
    "unpack_catalog",
    "validate_catalog",
    "verify_catalog_against_evidence",
    "VisualRangeRequest",
    "build_initial_planner_prompt",
    "planner_dependency_signature",
    "validate_planner_action",
]
